/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package id.app.tugas;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        homeScreen classUnderTest = new homeScreen();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
